// <auto-generated />
using System;
using Gæld.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gæld.Migrations
{
    [DbContext(typeof(DebtBookContext))]
    partial class DebtBookContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Gæld.Database.Models.Debt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Debts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = -30,
                            Date = new DateTime(2020, 10, 25, 15, 31, 26, 700, DateTimeKind.Local).AddTicks(8737),
                            PersonId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = -15,
                            Date = new DateTime(2020, 10, 25, 15, 31, 26, 702, DateTimeKind.Local).AddTicks(9049),
                            PersonId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 19,
                            Date = new DateTime(2020, 10, 25, 15, 31, 26, 702, DateTimeKind.Local).AddTicks(9049),
                            PersonId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 5000,
                            Date = new DateTime(2020, 10, 25, 15, 31, 26, 702, DateTimeKind.Local).AddTicks(9049),
                            PersonId = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = -5000,
                            Date = new DateTime(2020, 9, 25, 15, 31, 26, 702, DateTimeKind.Local).AddTicks(9049),
                            PersonId = 3
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1234,
                            Date = new DateTime(2020, 10, 10, 15, 31, 26, 702, DateTimeKind.Local).AddTicks(9049),
                            PersonId = 4
                        });
                });

            modelBuilder.Entity("Gæld.Database.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Carsten"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sebastian"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ermin Jensen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rayquaza"
                        });
                });

            modelBuilder.Entity("Gæld.Database.Models.Debt", b =>
                {
                    b.HasOne("Gæld.Database.Models.Person", "Person")
                        .WithMany("Debts")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
